spring.application.name=XyXarXpert
server.port=1212

spring.config.import=optional:classpath:private-info.properties
spring.datasource.url=jdbc:postgresql://localhost:5433/xxxpert
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

app.email-verification=false